### ISSUE TITLE
Why use `get_user_model`?

### ISSUE THREAD

**Issue by jbrucker** [ChanunyaO/KU-Lend#37]
https://github.com/ChanunyaO/KU-Lend/blob/e888c06b29a54dbb7366e8e4533723ffecfd131c/ku_lend/views.py#L41-L42

I don't understand why this is done.  Add a comment to explain rationale
and why this is necessary?

**Comment by ChanunyaO** [comment]
@jbrucker I thought it's necessary when I was working with this function, but I just find out that it's not. Thanks!!😁🙏
